AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Este es el stack de la consola web que acompana al bot
Resources:
  EmployeesBackend:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  WriteEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.employees.Proxy
      Runtime: java8
      CodeUri: s3://angramcab-bucket-for-lambda-code/41091103eed734392a9f92768d863f31
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId:
              Ref: EmployeesBackend
            Path: /Employee
            Method: POST
  Employees:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${EmployeesBackend}.execute-api.${AWS::Region}.amazonaws.com/Prod/
