
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Este es el stack de la consola web que acompana al bot
Resources: 
  EmployeesBackend:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  GetEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.employees.GetterEmployee
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
           Type: Api
           Properties:
             RestApiId: !Ref EmployeesBackend
             Path: /Employee/{id}
             Method: GET
  GetEmployees:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.employees.GetterEmployees
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /Employee
            Method: GET
  WriteEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.employees.Record
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
            TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /Employee
            Method: POST
  DeleteEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.employees.Deleter
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
            TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /Employee/{id}
            Method: DELETE
  # UpdateHotel:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: hotels.updateHotel
  #     Runtime: nodejs8.10
  #     CodeUri: src/
  #     Policies: AmazonDynamoDBFullAccess
  #     Environment:
  #       Variables:
  #           TABLE_NAME: !Ref Hotels
  #     Events:
  #       HotelChatbotBackend:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref HotelChatbotBackend
  #           Path: /Hotel/{hotelId}
  #           Method: PUT
  Employees: 
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName: Employees
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${EmployeesBackend}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

