
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Este es el stack de la consola web que acompana al bot
Resources: 
  EmployeesBackend:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  GetEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.services.GetterService
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 20
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
           Type: Api
           Properties:
             RestApiId: !Ref EmployeesBackend
             Path: /employees/{id}
             Method: GET
  GetEmployees:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.services.GetterAllService
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 20
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /employees
            Method: GET
  WriteEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.services.WriterService
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 20
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
            TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /employees
            Method: POST
  DeleteEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.services.DeleterService
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 20
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
            TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /employees/{id}
            Method: DELETE
  UpdateEmployee:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.angel.services.UpdaterService
      Runtime: java8
      CodeUri: build/distributions/employees-api-rest.zip
      MemorySize: 256
      Timeout: 20
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Employees
      Events:
        EmployeesBackend:
          Type: Api
          Properties:
            RestApiId: !Ref EmployeesBackend
            Path: /employees/{id}
            Method: PUT
  Employees: 
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName: Employees
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${EmployeesBackend}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

